### ISSUE TITLE
Assign keyboard shortcuts to open TextGrab

### ISSUE THREAD

**Issue by Sarpar12** [TheJoeFin/Text-Grab#58] opened 2021-09-02 23:08 UTC
You would do ctrl + shift + any key to open text edit, and maybe other shortcuts for fullscreen or grab frame, but if that's too much work, the shortcut would open the default one you chose in settings.

**Comment by Sarpar12** [comment] 2021-09-03 00:56
Oh didn't realize you need to have the process running to have a shortcut.

**Comment by supsm** [comment] 2021-09-03 05:49
Duplicate of #30

**Closed** 2021-11-19 23:48 UTC
