### ISSUE TITLE
Copies Cyrillic text with english/latin characters

### ISSUE THREAD

**Issue by Kenya-West** [TheJoeFin/Text-Grab#26] opened 2021-02-27 11:25 UTC
Previous versions of the app worked fine, but now I can't copy cyrillic texts.

For example, it copies this text:

> ЭТО ТЕСТОВЫЙ ТЕКСТ ДЛЯ КОПИРОВАНИЯ В ПРОГРАММУ 

as this one: 

> 310 TECTOBblVl TEKCT AJIR KOIUlPOBAHV19 B nporPAMMY

Windows 10 20H2, all the locales are `RU-ru` and the keyboard first language is russian.
TextGrab ver: 1.4.0.0

**Comment by TheJoeFin** [comment] 2021-02-27 14:07
Hello @Kenya-West, thank you for bringing this to my attention. I found the issue and it should be fixed in 1.5 which I will be releasing this weekend. 

I reproduced the bug on my computer and when the fix is applied I can now get the following result from the string you provided:

![Text-Grab-RU-BugFix](https://user-images.githubusercontent.com/7809853/109389582-b7613b00-78d2-11eb-88e1-0c71f93aef66.gif)

**Comment by TheJoeFin** [comment] 2021-02-27 15:54
I have submitted 1.5 to the store which should fix this issue. If it does not, feel free to reopen the issue.

**Comment by Kenya-West** [comment] 2021-02-27 15:57
@TheJoeFin thanks for fast response! Yes, I confirm that your resulting text on the picture is correct. Waiting for update then. Thanks for your effort!

**Comment by Kenya-West** [comment] 2021-03-16 09:58
Hello! The bug still persists in version 1.5.0.0

**Comment by TheJoeFin** [comment] 2021-03-16 11:00
This is my language flyout and this is the result of my clipboard. Tested on Version 1.5, can you share yours.

With Russian Selected:
`ЭТО ТЕСТОВЫЙ ТЕКСТ ДЛЯ КОПИРОВАНИЯ В ПРОГРАММУ`

with English Selected
`3T0 TECTOBblV1 TEKCT KO[WIPOBAHVIA B rlPOrPAMMY`

![image](https://user-images.githubusercontent.com/7809853/111297266-6d3ec000-861b-11eb-8ab8-c2a084fc1fc9.png)

![image](https://user-images.githubusercontent.com/7809853/111298544-d7a43000-861c-11eb-99f8-1a2691944826.png)

**Comment by TheJoeFin** [comment] 2021-04-03 21:27
found and fixed another bug. Should work better with 2.0

**Comment by TheJoeFin** [comment] 2021-04-06 14:50
@Kenya-West I tested the fix in my environment, could you verify Text Grab 2.0 fixes this issue for you?

**Comment by Kenya-West** [comment] 2021-04-06 16:28
> @Kenya-West I tested the fix in my environment, could you verify Text Grab 2.0 fixes this issue for you?

OK, tomorrow I'll do this

**Comment by Kenya-West** [comment] 2021-04-07 11:30
@TheJoeFin the app copies texts according to selected keyboard language. If you have selected English keyboard layout and try to copy Russian text, the bug persists. If you currently use Russian keyboard and copy Russian text, then in works correctly as supposed to be (the same for English texts, too).

Is this the expected behaviour when the recognition depends on currently selected keyboard language? If so, then issue can be closed.

**Comment by zybexXL** [comment] 2021-04-07 12:02
@Kenya-West, it's not enough to install the Keyboard layout, you need to install the full RU Language Pack (which includes the OCR component).

**Comment by TheJoeFin** [comment] 2021-04-07 13:05
> Is this the expected behaviour when the recognition depends on currently selected keyboard language? If so, then issue can be closed.

Yes. The OCR Engine needs to know what language it is trying to detect, this is done by changing the Windows keyboard language before activating Text Grab. 

Since it seems like Text Grab is working as intended I am going to close this issue.

**Closed by TheJoeFin** 2021-04-07 13:05 UTC
Labels: bug

**Comment by sitex** [comment] 2024-01-27 10:54
Text Grab 4.3.1 - same error

**Comment by TheJoeFin** [comment] 2024-01-27 15:29
@sitex can you open a new issue and provide screenshots of the problem and your language settings
